# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tokenId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
