# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20180620_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='degrees',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='orientation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
