# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20180621_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='degrees',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='orientation',
            new_name='y',
        ),
        migrations.AddField(
            model_name='car',
            name='z',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
