# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20180624_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='latitude_dst',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude_dst',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
