# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20180627_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('alertAccident', models.BooleanField()),
                ('alertStatus', models.BooleanField()),
                ('alertSpeed', models.BooleanField()),
                ('alertHelp', models.BooleanField()),
                ('alertEvent', models.BooleanField()),
                ('alertCurve', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='latitude_dst',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='longitude_dst',
            field=models.CharField(max_length=50),
        ),
    ]
