# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20180628_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('frozen_road', models.BooleanField()),
                ('dangerous_curve', models.BooleanField()),
            ],
        ),
    ]
