# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
