# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
