# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_car_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
