# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_auto_20180726_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='latitude_old',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='longitude_old',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
