# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_alert_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='nid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
